[build]
  command = ""
  functions = "functions"
  publish = "."

[functions]
  directory = "functions"
  node_bundler = "esbuild"

# API requests should be handled first
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[dev]
  port = 9100  # Dedicated auth server port (avoids conflicts with other apps)
  open = false
  autoLaunch = false

# Note: CORS headers are handled dynamically in the functions themselves
# See functions/middleware/cors.ts for CORS configuration
