[build]
  command = ""
  functions = "functions"
  publish = "."

[functions]
  directory = "functions"
  node_bundler = "esbuild"

# API requests should be handled first
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[dev]
  port = 8888  # Port for Netlify Dev server
  open = false
  autoLaunch = false
  functions = "auth-service/functions"  # Local dev needs full path from repo root

# Note: CORS headers are handled dynamically in the functions themselves
# See auth-service/functions/middleware/cors.ts for CORS configuration
