[build]
  command = ""
  functions = 'auth-service/functions'
  publish = "auth-service"

[functions]
  directory = "auth-service/functions"
  node_bundler = "esbuild"

# API requests should be handled first
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[dev]
  port = 8888  # Port for Netlify Dev server
  open = false
  autoLaunch = false

# Note: CORS headers are handled dynamically in the functions themselves
# See auth-service/functions/middleware/cors.ts for CORS configuration
